Repository appsignal/appsignal-nodejs, pull requests merged in 2020-07, with the labels that each got.

#190 Add https instrumentation
  packages/nodejs/src/client.ts
  packages/nodejs/src/instrumentation/http/http.ts
  packages/nodejs/src/instrumentation/http/https.ts
  packages/nodejs/src/instrumentation/http/index.ts
  packages/nodejs/src/instrumentation/index.ts
Labels: enhancement

#195 Redis integration
  package.json
  packages/nodejs/src/client.ts
  packages/nodejs/src/instrumentation/redis/index.ts
  yarn.lock
Labels: enhancement

#214 Bump agent to v-c8f8185
  packages/nodejs-ext/scripts/extension/constants.js
Labels: bug

#215 Move postgres integration to core, deprecate @appsignal/pg
  packages/nodejs/src/client.ts
  packages/nodejs/src/instrumentation/pg/index.ts
  packages/nodejs/src/instrumentation/pg/patches/index.ts
  packages/pg/src/index.ts
Labels: chore

#211 Add apollo-server plugin
  package.json
  packages/apollo-server/.gitignore
  packages/apollo-server/.npmignore
  packages/apollo-server/README.md
  packages/apollo-server/jest.config.js
  packages/apollo-server/package.json
  packages/apollo-server/src/index.ts
  packages/apollo-server/tsconfig.json
  yarn.lock
Labels: feature
