Repository appsignal/appsignal-nodejs, pull requests merged in 2020-04, with the labels that each got.

#74 Express instrumentation with route matching
  packages/express/src/index.ts
  packages/express/src/middleware/index.ts
  packages/nodejs/src/client.ts
  packages/nodejs/src/index.ts
  packages/nodejs/src/interfaces/tracer.ts
  packages/nodejs/src/noops/tracer.ts
Labels: feature

#79 Move extension into its own package
  .travis.yml
  package.json
  packages/nodejs-ext/.gitignore
  packages/nodejs-ext/binding.gyp
  packages/nodejs-ext/ext/appsignal_extension.cpp
  packages/nodejs-ext/package.json
  packages/nodejs-ext/scripts/extension.js
  packages/nodejs-ext/scripts/extension/constants.js
  packages/nodejs-ext/scripts/extension/helpers.js
  packages/nodejs-ext/scripts/report.js
  packages/nodejs-ext/src/index.ts
  packages/nodejs-ext/tsconfig.json
  packages/nodejs/package.json
  packages/nodejs/scripts/extension/constants.js
  packages/nodejs/src/__tests__/agent.test.ts
  packages/nodejs/src/agent.ts
  packages/nodejs/src/client.ts
  packages/nodejs/src/config.ts
  packages/nodejs/src/extension.ts
  packages/nodejs/src/interfaces/extension.ts
  packages/nodejs/src/internal/dataarray.ts
  packages/nodejs/src/internal/datamap.ts
  packages/nodejs/src/metrics.ts
  packages/nodejs/src/span.ts
Labels: enhancement

#91 Fix for bug reported in #29
  packages/nodejs-ext/scripts/extension.js
  packages/nodejs-ext/scripts/report.js
Labels: bug

#92 Figure out if using musl libc instead of depending on APPSIGNAL_BUILD_FOR_MUSL
  packages/nodejs-ext/scripts/extension/helpers.js
  packages/nodejs-ext/scripts/report.js
Labels: bug

#98 Move CI to Semaphore
  .semaphore/semaphore.yml
  .travis.yml
  package.json
Labels: chore
