Repository appsignal/appsignal-nodejs, pull requests merged in 2021-08, with the labels that each got.

#422 Build matrix tests check
  Rakefile
Labels: chore, dev happiness

#420 Koa integration test
  .semaphore/semaphore.yml
  build_matrix.yml
  packages/express/test/integration_spec.rb
  packages/koa/test/Gemfile
  packages/koa/test/example/index.js
  packages/koa/test/example/package-lock.json
  packages/koa/test/example/package.json
  packages/koa/test/integration_spec.rb
Labels: chore

#419 Express integration test
  .semaphore/semaphore.yml
  build_matrix.yml
  packages/express/test/Gemfile
  packages/express/test/Gemfile.lock
  packages/express/test/example/index.js
  packages/express/test/example/package-lock.json
  packages/express/test/example/package.json
Labels: chore

#423 Fix middleware path detection for Express
  packages/express/src/middleware/index.ts
  packages/express/test/example/admin.js
  packages/express/test/example/index.js
  packages/express/test/integration_spec.rb
Labels: bug

#424 Refactor integrations tests
  .gitignore
  .semaphore/semaphore.yml
  build_matrix.yml
  packages/express/test/.rspec
  packages/express/test/example/index.js
  packages/express/test/spec/integration_spec.rb
  packages/express/test/spec/spec_helper.rb
  packages/koa/test/.rspec
  packages/koa/test/Gemfile.lock
  packages/koa/test/example/index.js
  packages/koa/test/spec/integration_spec.rb
  packages/koa/test/spec/spec_helper.rb
  packages/nextjs/test/.rspec
  packages/nextjs/test/example/server.js
  packages/nextjs/test/spec/integration_spec.rb
  packages/nextjs/test/spec/spec_helper.rb
  script/test_package_integration
Labels: chore, dev happiness

#425 Refactor integration tests to reuse helpers
  packages/express/test/spec/integration_spec.rb
  packages/express/test/spec/spec_helper.rb
  packages/koa/test/spec/integration_spec.rb
  packages/koa/test/spec/spec_helper.rb
  packages/nextjs/test/example/server.js
  packages/nextjs/test/spec/integration_spec.rb
  packages/nextjs/test/spec/spec_helper.rb
  test/support/app_runner.rb
Labels: chore, dev happiness

#427 Bump agent to 0f40689
  packages/nodejs-ext/.changesets/bump-agent-0f40689.md
  packages/nodejs-ext/scripts/extension/constants.js
Labels: chore

#428 Use fetch_root_span_id helper in integration specs
  packages/express/test/spec/integration_spec.rb
  packages/express/test/spec/spec_helper.rb
  packages/koa/test/spec/integration_spec.rb
  packages/koa/test/spec/spec_helper.rb
  packages/nextjs/test/spec/integration_spec.rb
  packages/nextjs/test/spec/spec_helper.rb
  test/integration/support.rb
  test/integration/support/integration_helper.rb
Labels: chore, dev happiness

#431 Fix integration test packages
  .gitignore
  .semaphore/semaphore.yml
  Rakefile
  package-lock.json
  package.json
  packages/apollo-server/package.json
  packages/express/package.json
  packages/express/test/example/package-lock.json
  packages/express/test/example/package.json
  packages/express/test/spec/integration_spec.rb
  packages/koa/package.json
  packages/koa/test/example/package-lock.json
  packages/koa/test/example/package.json
  packages/koa/test/spec/integration_spec.rb
  packages/nextjs/package.json
  packages/nextjs/test/example/package-lock.json
  packages/nextjs/test/example/package.json
  packages/nextjs/test/spec/integration_spec.rb
  packages/nodejs/package.json
  script/install_test_example_packages
  script/test_package_integration
  test/integration/support/app_runner.rb
Labels: chore

#432 Drop support for Node.js 10 and 11
  .semaphore/semaphore.yml
  .tool-versions
  build_matrix.yml
  package.json
  packages/nodejs-ext/.changesets/drop-node-js-10-and-11-support.md
  packages/nodejs-ext/package.json
  packages/nodejs/.changesets/drop-node-js-10-and-11-support.md
  packages/nodejs/package.json
Labels: chore

#433 Add Apollo integration tests
  .semaphore/semaphore.yml
  build_matrix.yml
  packages/apollo-server/test/.rspec
  packages/apollo-server/test/Gemfile
  packages/apollo-server/test/Gemfile.lock
  packages/apollo-server/test/example/index.js
  packages/apollo-server/test/example/package.json
  packages/apollo-server/test/spec/integration_spec.rb
  packages/apollo-server/test/spec/spec_helper.rb
Labels: chore

#434 Bump to agent 0318770
  packages/nodejs-ext/.changesets/bump-agent-0318770.md
  packages/nodejs-ext/scripts/extension/constants.js
Labels: chore

#435 Fix timestamp calculation
  packages/nodejs/.changesets/timestamp-fix.md
  packages/nodejs/src/__tests__/utils.test.ts
  packages/nodejs/src/utils.ts
Labels: bug
