Repository appsignal/appsignal-nodejs, pull requests merged in 2021-09, with the labels that each got.

#440 Add mirror download support
  packages/nodejs-ext/.changesets/add-mirrors-to-download-the-agent.md
  packages/nodejs-ext/scripts/extension.js
  packages/nodejs-ext/scripts/extension/constants.js
Labels: chore

#441 Fix code style in extension.js script
  packages/express/jest.config.js
  packages/nodejs-ext/scripts/extension.js
  packages/nodejs-ext/scripts/extension/constants.js
Labels: chore

#442 Remove outputPath from downloadData in installer
  packages/nodejs-ext/scripts/extension.js
Labels: chore

#444 Add Prettier to CI build
  .semaphore/semaphore.yml
  build_matrix.yml
  package.json
  packages/nodejs/src/__tests__/config.test.ts
  packages/nodejs/src/__tests__/data.test.ts
Labels: chore, dev happiness

#439 Support local extension files for installer
  .semaphore/semaphore.yml
  Rakefile
  packages/nodejs-ext/.changesets/support-local-installs-using-npm-install.md
  packages/nodejs-ext/package.json
  packages/nodejs-ext/scripts/extension.js
Labels: chore

#446 Add rootSpan and addError helpers
  package-lock.json
  package.json
  packages/apollo-server/package.json
  packages/apollo-server/src/index.ts
  packages/express/package.json
  packages/express/src/middleware/index.ts
  packages/koa/README.md
  packages/koa/package.json
  packages/nextjs/package.json
  packages/nodejs/.changesets/add-root-span-and-add-error-helpers.md
  packages/nodejs/package.json
  packages/nodejs/src/__tests__/scope.test.ts
  packages/nodejs/src/__tests__/tracer.test.ts
  packages/nodejs/src/demo.ts
  packages/nodejs/src/instrumentation/http/lifecycle/outgoing.ts
  packages/nodejs/src/instrumentation/pg/index.ts
  packages/nodejs/src/instrumentation/pg/patches/index.ts
  packages/nodejs/src/instrumentation/redis/index.ts
  packages/nodejs/src/noops/span.ts
  packages/nodejs/src/noops/tracer.ts
  packages/nodejs/src/scope.ts
  packages/nodejs/src/span.ts
  packages/nodejs/src/tracer.ts
Labels: bug, support

#447 Deprecate addError functions
  package-lock.json
  package.json
  packages/apollo-server/package.json
  packages/express/package.json
  packages/koa/package.json
  packages/nextjs/package.json
  packages/nodejs/.changesets/deprecate-adderror-function.md
  packages/nodejs/package.json
  packages/nodejs/src/noops/span.ts
  packages/nodejs/src/span.ts
Labels: bug

#449 Bump agent to 7376537
  packages/nodejs-ext/.changesets/bump-agent-to-7376537.md
  packages/nodejs-ext/scripts/extension/constants.js
Labels: enhancement

#450 Add sendError helper to Tracer object
  package-lock.json
  package.json
  packages/apollo-server/package.json
  packages/express/package.json
  packages/koa/package.json
  packages/nextjs/package.json
  packages/nodejs/.changesets/add-senderror-helper-to-tracer.md
  packages/nodejs/package.json
  packages/nodejs/src/__tests__/tracer.test.ts
  packages/nodejs/src/noops/tracer.ts
  packages/nodejs/src/tracer.ts
Labels: chore, enhancement
