Repository appsignal/appsignal-nodejs, pull requests merged in 2021-05, with the labels that each got.

#383 Handle all non-dynamic paths as static routes
  packages/nextjs/src/handler.ts
  packages/nextjs/test/example/pages/blog/index.js
  packages/nextjs/test/example/pages/post/[id].js
  packages/nextjs/test/integration_spec.rb
Labels: bug

#387 Wrap filepath in quotes in tar command
  packages/nodejs-ext/scripts/extension.js
Labels: bug

#392 Add --[no-]send-report options to diagnose
  packages/nodejs/.changesets/send-report-and-no-send-report-options.md
  packages/nodejs/bin/diagnose
Labels: enhancement

#395 Update mono to 0.2.0
  .semaphore/semaphore.yml
  script/setup
Labels: chore

#396 Make APPSIGNAL_BUILD_FOR_MUSL behavior consistent
  packages/nodejs-ext/.changesets/.gitkeep
  packages/nodejs-ext/.changesets/musl-build-flag.md
  packages/nodejs-ext/jest.config.js
  packages/nodejs-ext/package.json
  packages/nodejs-ext/scripts/report.js
  packages/nodejs-ext/scripts/report.test.js
Labels: bug

#397 Update to mono v0.3.0
  README.md
  package.json
  script/setup
Labels: chore

#394 Add mono to project
  .semaphore/semaphore.yml
  .tool-versions
  README.md
  lerna.json
  mono.yml
  package-lock.json
  package.json
  packages/apollo-server/package-lock.json
  packages/express/package-lock.json
  packages/koa/package-lock.json
  packages/nextjs/package-lock.json
  packages/nodejs-ext/package-lock.json
  packages/nodejs-ext/package.json
  packages/nodejs/package-lock.json
  packages/nodejs/package.json
  script/setup
Labels: enhancement
