Repository appsignal/appsignal-nodejs, pull requests merged in 2021-12, with the labels that each got.

#527 Update Git linter (Lintje) to 0.6.1
  script/lint_git
Labels: chore, dev happiness

#528 Update mono to 0.6.0
  script/setup
Labels: chore, dev happiness

#531 Allow transmitters to use cafile
  packages/nodejs/.changesets/cafilepath-works-for-diagnose-script-external-requests.md
  packages/nodejs/src/cli/diagnose.ts
  packages/nodejs/src/diagnose.ts
  packages/nodejs/src/transmitter.ts
Labels: bug

#534 Add helper for globally stored client
  packages/nodejs/.changesets/add-helper-to-access-the-globally-stored-appsignal-client.md
  packages/nodejs/src/__tests__/client.test.ts
  packages/nodejs/src/client.ts
Labels: enhancement, roadmap
