Repository appsignal/appsignal-nodejs, pull requests merged in 2021-11, with the labels that each got.

#474 Fix diagnose report's Push API key transmission
  packages/nodejs/.changesets/diagnose-api-key-transmission.md
  packages/nodejs/src/cli/diagnose.ts
  packages/nodejs/src/diagnose.ts
Labels: bug

#476 Bump agent to 09308fb
  packages/nodejs-ext/.changesets/bump-agent-to-09308fb.md
  packages/nodejs-ext/scripts/extension/constants.js
  packages/nodejs/src/version.ts
Labels: enhancement

#482 Implement config validation
  package-lock.json
  packages/nodejs/.changesets/config-is-not-considered-valid-anymore-when-apikey-is-missing.md
  packages/nodejs/src/__tests__/client.test.ts
  packages/nodejs/src/__tests__/config.test.ts
  packages/nodejs/src/client.ts
  packages/nodejs/src/config.ts
Labels: bug

#496 Add tests for config module
  packages/nodejs/src/__tests__/config.test.ts
Labels: chore

#498 Remove unsupported Node versions from build matrix
  .semaphore/semaphore.yml
  build_matrix.yml
Labels: chore

#499 Add AppSignal client to global object
  packages/nodejs/.changesets/appsignal-client-is-available-in-global-object.md
  packages/nodejs/src/__tests__/client.test.ts
  packages/nodejs/src/client.ts
  packages/nodejs/vendor.d.ts
Labels: enhancement, roadmap

#500 Deprecate using a filename in logPath
  packages/nodejs/.changesets/deprecate-passing-a-file-to-logpath-config-option.md
  packages/nodejs/src/__tests__/config.test.ts
  packages/nodejs/src/config.ts
Labels: chore

#504 Change global augmentation for newer TS
  packages/nodejs/.changesets/fix-compatibility-for-global-object-augmentation.md
  packages/nodejs/global.d.ts
  packages/nodejs/tsconfig.json
  packages/nodejs/vendor.d.ts
Labels: bug

#508 Check if logPath is a writable dir
  packages/nodejs/.changesets/logpath-config-option-only-allows-writable-paths--if-the-provided-path-is-not-writable,-it'll-automatically-change-to-default-os-tmp-path-after-a-warning-.md
  packages/nodejs/src/__tests__/config.test.ts
  packages/nodejs/src/__tests__/diagnose.test.ts
  packages/nodejs/src/config.ts
Labels: bug

#512 Fix writable path check in diagnose
  packages/nodejs/.changesets/fix-writable-check-in-diagnose-report.md
  packages/nodejs/src/diagnose.ts
Labels: bug

#511 Fix diagnose log_dir_path value
  packages/nodejs/.changesets/fix-diagnose-log_dir_path-path.md
  packages/nodejs/src/diagnose.ts
Labels: bug

#523 Update package-lock.json on mono publish
  mono.yml
Labels: chore
