Repository appsignal/appsignal-nodejs, pull requests merged in 2022-07, with the labels that each got.

#707 Map requestHeaders config opt to OpenTelemetry
  src/client.ts
Labels: feature, opentelemetry

#708 Update OpenTelemetry dependencies for HTTP errors
  package-lock.json
  package.json
Labels: chore

#711 Accept all case diagnose send report confirm input
  .changesets/accept-uppercase-input-in-diagnose-tool-send-report-prompt.md
  src/cli/diagnose.ts
Labels: bug

#714 Add error event listener correctly in README
  packages/koa/README.md
Labels: chore

#712 Bump agent to 06391fb
  .changesets/bump-agent-06391fb.md
  scripts/extension/support/constants.js
  src/__tests__/span_processor.test.ts
Labels: enhancement
