Repository appsignal/appsignal-nodejs, pull requests merged in 2022-08, with the labels that each got.

#716 Add OTel tracer provider as a client property
  src/__tests__/client.test.ts
  src/client.ts
Labels: discuss, opentelemetry

#718 Do not instrument Koa generator middleware
  packages/koa/.changesets/do-not-break-requests-using-legacy-generator-middleware.md
  packages/koa/README.md
  packages/koa/src/patches/index.ts
  packages/koa/test/example/index.js
Labels: bug

#720 Postgres otel test app
  .semaphore/semaphore.yml
  build_matrix.yml
  src/client.ts
  test/express-postgres/app/.gitignore
  test/express-postgres/app/Dockerfile
  test/express-postgres/app/package-lock.json
  test/express-postgres/app/package.json
  test/express-postgres/app/run.sh
  test/express-postgres/app/src/app.ts
  test/express-postgres/app/src/appsignal.ts
  test/express-postgres/app/tsconfig.json
  test/express-postgres/docker-compose.yml
  test/express-postgres/tests/.rspec
  test/express-postgres/tests/Dockerfile
  test/express-postgres/tests/Gemfile
  test/express-postgres/tests/Gemfile.lock
  test/express-postgres/tests/spec/app_spec.rb
  test/express-postgres/tests/spec/spec_helper.rb
  test/integration_helper.rb
  test/koa-mysql/tests/spec/app_spec.rb
Labels: feature, opentelemetry

#722 Graphql instrumentation
  .semaphore/semaphore.yml
  build_matrix.yml
  src/client.ts
  test/express-apollo/app/.gitignore
  test/express-apollo/app/Dockerfile
  test/express-apollo/app/package-lock.json
  test/express-apollo/app/package.json
  test/express-apollo/app/run.sh
  test/express-apollo/app/src/app.ts
  test/express-apollo/app/src/appsignal.ts
  test/express-apollo/app/tsconfig.json
  test/express-apollo/docker-compose.yml
  test/express-apollo/tests/.rspec
  test/express-apollo/tests/Dockerfile
  test/express-apollo/tests/Gemfile
  test/express-apollo/tests/Gemfile.lock
  test/express-apollo/tests/spec/app_spec.rb
  test/express-apollo/tests/spec/spec_helper.rb
  test/express-yoga/app/.gitignore
  test/express-yoga/app/Dockerfile
  test/express-yoga/app/package-lock.json
  test/express-yoga/app/package.json
  test/express-yoga/app/run.sh
  test/express-yoga/app/src/app.ts
  test/express-yoga/app/src/appsignal.ts
  test/express-yoga/app/tsconfig.json
  test/express-yoga/docker-compose.yml
  test/express-yoga/tests/.rspec
  test/express-yoga/tests/Dockerfile
  test/express-yoga/tests/Gemfile
  test/express-yoga/tests/Gemfile.lock
  test/express-yoga/tests/spec/app_spec.rb
  test/express-yoga/tests/spec/spec_helper.rb
  test/integration_helper.rb
Labels: feature, opentelemetry

#723 Update error handling in demo script
  src/demo.ts
Labels: bug
