Repository appsignal/appsignal-nodejs, pull requests merged in 2022-02, with the labels that each got.

#587 Update Span type used in ScopeManager
  packages/nodejs/.changesets/update-span-type-in-scopemanager.md
  packages/nodejs/src/scope.ts
Labels: chore

#588 Fix the extension path for local install detection
  packages/nodejs/scripts/extension/support/helpers.js
Labels: bug

#586 Update span tests
  packages/nodejs/src/__tests__/span.test.ts
Labels: chore

#589 Test the Transmitter class
  package-lock.json
  packages/nodejs/package.json
  packages/nodejs/src/__tests__/transmitter.test.ts
  packages/nodejs/src/transmitter.ts
Labels: chore

#592 Add Span.toObject function, replacing Span.toJSON
  packages/nodejs/.changesets/remove-span-tojson-function.md
  packages/nodejs/src/__tests__/scope.test.ts
  packages/nodejs/src/__tests__/span.test.ts
  packages/nodejs/src/__tests__/tracer.test.ts
  packages/nodejs/src/interfaces/span.ts
  packages/nodejs/src/noops/span.ts
  packages/nodejs/src/span.ts
Labels: chore

#591 Add more tests for Span type
  packages/nodejs/.changesets/remove-span-tojson-function.md
  packages/nodejs/src/__tests__/scope.test.ts
  packages/nodejs/src/__tests__/span.test.ts
  packages/nodejs/src/__tests__/tracer.test.ts
  packages/nodejs/src/interfaces/span.ts
  packages/nodejs/src/noops/span.ts
  packages/nodejs/src/span.ts
Labels: chore

#594 Update confusing install messages for local build
  packages/nodejs/scripts/extension/extension.js
Labels: chore, dev happiness

#595 Make noop object initialization consistent
  packages/nodejs/.changesets/improve-memory-usage-when-extension-is-not-initialized.md
  packages/nodejs/src/client.ts
Labels: chore

#597 Reuse client getter helper
  packages/nodejs/src/client.ts
Labels: chore

#593 Bump the base Node.js version for development
  .tool-versions
Labels: chore, dev happiness

#600 Test the extension download function
  packages/nodejs/scripts/extension/extension.js
  packages/nodejs/scripts/extension/extension.test.js
Labels: chore

#601 Support arm64 host for tests
  packages/nodejs/scripts/extension/report.test.js
Labels: chore

#606 Add tests for http outgoing integration
  packages/nodejs/src/instrumentation/http/lifecycle/__tests__/outgoing.test.ts
  packages/nodejs/test/registry.ts
Labels: chore

#609 Remove experimental module
  packages/nodejs/.changesets/remove-unused-experimental-module.md
  packages/nodejs/src/experimental.ts
  packages/nodejs/src/index.ts
Labels: chore

#607 Ignore script test files in published package
  packages/nodejs/.changesets/do-not-ship-test-files.md
  packages/nodejs/.npmignore
  packages/nodejs/scripts/extension/__tests__/extension.failure.test.js
  packages/nodejs/scripts/extension/__tests__/extension.test.js
  packages/nodejs/scripts/extension/__tests__/report.test.js
Labels: chore

#610 Update `@appsignal/types` dependency to 3.0.0
  package-lock.json
  package.json
  packages/koa/.changesets/update-appsignal-types-dependency-to-3-0-0-.md
  packages/koa/package.json
  packages/nodejs/.changesets/update-appsignal-types-dependency-to-3-0-0-.md
  packages/nodejs/package.json
Labels: chore

#611 Show extension load error on require
  packages/nodejs/.changesets/show-extension-load-errors-when-required.md
  packages/nodejs/src/__tests__/extension.failure.test.ts
  packages/nodejs/src/extension.ts
  packages/nodejs/src/extension_wrapper.ts
Labels: bug

#612 Implement stop method for probes
  packages/nodejs/.changesets/stop-minutely-probes-when-stopping-appsignal.md
  packages/nodejs/src/__tests__/client.test.ts
  packages/nodejs/src/__tests__/metrics.test.ts
  packages/nodejs/src/__tests__/probes.test.ts
  packages/nodejs/src/client.ts
  packages/nodejs/src/instrumentation/http/lifecycle/__tests__/outgoing.test.ts
  packages/nodejs/src/interfaces/probes.ts
  packages/nodejs/src/metrics.ts
  packages/nodejs/src/noops/index.ts
  packages/nodejs/src/noops/metrics.ts
  packages/nodejs/src/noops/probes.ts
  packages/nodejs/src/probes/index.ts
Labels: enhancement

#613 Fix tests on client start
  packages/nodejs/src/__tests__/client.test.ts
Labels: chore

#614 Restore, reset and clear mocks between tests
  packages/nodejs/jest.config.js
  packages/nodejs/scripts/extension/__tests__/extension.test.js
  packages/nodejs/src/__tests__/bootstrap.test.ts
  packages/nodejs/src/__tests__/client.test.ts
  packages/nodejs/src/__tests__/config.test.ts
  packages/nodejs/src/__tests__/diagnose.test.ts
  packages/nodejs/src/__tests__/span.test.ts
  packages/nodejs/src/__tests__/transmitter.test.ts
Labels: chore

#619 Bump agent to v-bbc830a
  packages/nodejs/.changesets/bump-agent-to-v-bbc830a.md
  packages/nodejs/scripts/extension/support/constants.js
Labels: chore

#621 Bump agent to v-f57e6cb
  packages/nodejs/.changesets/bump-agent-to-v-f57e6cb.md
  packages/nodejs/scripts/extension/support/constants.js
Labels: enhancement

#620 Add centralized logger
  package-lock.json
  packages/nodejs/.changesets/add-centralized-logger.md
  packages/nodejs/package.json
  packages/nodejs/src/__tests__/client.test.ts
  packages/nodejs/src/__tests__/logger.test.ts
  packages/nodejs/src/bootstrap.ts
  packages/nodejs/src/client.ts
  packages/nodejs/src/instrument.ts
  packages/nodejs/src/interfaces/client.ts
  packages/nodejs/src/logger.ts
  packages/nodejs/src/span.ts
Labels: bug
