Repository appsignal/appsignal-nodejs, pull requests merged in 2022-01, with the labels that each got.

#538 Check if the process is running in a container from the extension
  packages/nodejs-ext/.changesets/runningincontainer-function-is-now-available-from-the-extension.md
  packages/nodejs-ext/ext/appsignal_extension.cpp
  packages/nodejs/.changesets/extension-now-checks-running-in-container.md
  packages/nodejs/src/diagnose.ts
  packages/nodejs/src/extension.ts
Labels: chore

#539 Handle request errors on diagnose HTTP transmitter
  packages/nodejs/.changesets/handle-request-errors-on-diagnose-http-transmitter-.md
  packages/nodejs/src/diagnose.ts
  packages/nodejs/src/transmitter.ts
Labels: chore

#542 Bump agent version
  packages/nodejs-ext/.changesets/bump-appsignal-agent-version.md
Labels: chore

#543 Add hostname tag to V8 probe gauges
  packages/nodejs/.changesets/add-hostname-tag-to-v8-probe-gauges.md
  packages/nodejs/src/__tests__/probes.test.ts
  packages/nodejs/src/probes/v8/index.ts
Labels: bug

#547 Fix `enableMinutelyProbes` behaviour
  packages/nodejs/.changesets/fix-enableminutelyprobes-behaviour.md
  packages/nodejs/.changesets/implement-unregister-method-for-probes.md
  packages/nodejs/src/__tests__/bootstrap.test.ts
  packages/nodejs/src/__tests__/metrics.test.ts
  packages/nodejs/src/__tests__/probes.test.ts
  packages/nodejs/src/bootstrap.ts
  packages/nodejs/src/client.ts
  packages/nodejs/src/interfaces/probes.ts
  packages/nodejs/src/metrics.ts
  packages/nodejs/src/noops/index.ts
  packages/nodejs/src/noops/metrics.ts
  packages/nodejs/src/noops/probes.ts
  packages/nodejs/src/probes/index.ts
Labels: bug

#549 Allow expected process name to be a path
  packages/nodejs/src/__tests__/config.test.ts
Labels: dev happiness

#558 Fix the CI build to include intentional failures
  .semaphore/semaphore.yml
  build_matrix.yml
  packages/nodejs/jest.config.js
  packages/nodejs/package.json
Labels: chore

#557 Fix extension function fallbacks
  packages/nodejs/.changesets/fix-extension-fallback-functions.md
  packages/nodejs/src/__tests__/extension.failure.test.ts
  packages/nodejs/src/extension.ts
  packages/nodejs/src/extension_wrapper.ts
Labels: bug

#554 Improve extension loading state and starting
  packages/nodejs/.changesets/change-the-way-the-extension-is-started.md
  packages/nodejs/.changesets/fix-extension-fallback-functions.md
  packages/nodejs/.changesets/improve-extension-loading.md
  packages/nodejs/src/__tests__/client.test.ts
  packages/nodejs/src/__tests__/extension.failure.test.ts
  packages/nodejs/src/__tests__/extension.test.ts
  packages/nodejs/src/client.ts
  packages/nodejs/src/diagnose.ts
  packages/nodejs/src/extension.ts
  packages/nodejs/src/extension_wrapper.ts
  packages/nodejs/src/interfaces/extension_wrapper.ts
Labels: enhancement

#562 Update CI with new install report location
  .semaphore/semaphore.yml
  Rakefile
  build_matrix.yml
Labels: chore

#561 Remove cpu and os fields from package.json
  packages/nodejs/.changesets/remove-package-json-os-and-cpu-fields.md
  packages/nodejs/package.json
Labels: chore

#566 Lock Redis supported version to 3.x.x
  packages/nodejs/.changesets/lock-redis-version-to-3.md
  packages/nodejs/src/instrumentation/redis/index.ts
Labels: bug, support

#576 Bump to Next.js version 12
  package-lock.json
Labels: chore

#583 Bump json-schema and dependent packages
  package-lock.json
Labels: security
