Repository appsignal/appsignal-nodejs, pull requests merged in 2022-11, with the labels that each got.

#777 Add fs module support
  .changesets/add-fs-module-support.md
  package-lock.json
  package.json
  src/client.ts
  src/span_processor.ts
  test/express-redis/app/package-lock.json
  test/express-redis/app/src/app.ts
  test/express-redis/tests/spec/app_spec.rb
Labels: enhancement

#779 Bump agent version to b644bb6
  scripts/extension/support/constants.js
Labels: chore

#782 Add helpers optional span argument test
  src/__tests__/helpers.test.ts
Labels: chore

#783 Bump agent version to 734d016
  scripts/extension/support/constants.js
Labels: chore

#784 Bump agent to version fbdbe33
  .changesets/instrument-outgoing-http-requests.md
  scripts/extension/support/constants.js
Labels: enhancement

#797 Set RuboCop Ruby target version
  .ruby-version
  Gemfile.lock
  test/helpers/span.rb
Labels: chore, dev happiness

#796 Move integration test config helpers to module
  test/express-apollo/tests/spec/app_spec.rb
  test/express-mongoose/tests/spec/app_spec.rb
  test/express-postgres/tests/spec/app_spec.rb
  test/express-prisma-mongo/tests/spec/app_spec.rb
  test/express-prisma-postgres/tests/spec/app_spec.rb
  test/express-redis/tests/spec/app_spec.rb
  test/express-yoga/tests/spec/app_spec.rb
  test/fastify/tests/spec/app_spec.rb
  test/helpers/config_helper.rb
  test/helpers/integration_helper.rb
  test/helpers/span.rb
  test/koa-mongo/tests/spec/app_spec.rb
  test/koa-mysql/tests/spec/app_spec.rb
  test/nestjs/tests/spec/app_spec.rb
  test/nextjs/tests/spec/app_spec.rb
Labels: chore, dev happiness

#789 Update README to v3 behavior
  README.md
Labels: chore, writing

#802 Add noop user and integration logger
  src/__tests__/client.test.ts
  src/__tests__/integration_logger.test.ts
  src/__tests__/logger.test.ts
  src/client.ts
  src/integration_logger.ts
  src/logger.ts
  src/noops/index.ts
  src/noops/integration_logger.ts
  src/noops/logger.ts
Labels: chore

#799 Add request params support for Fastify
  .changesets/record-parameters-for-fastify-apps.md
  package-lock.json
  package.json
  src/client.ts
  test/fastify/app/package-lock.json
Labels: enhancement

#805 Fix test suite for Node.js 19.1
  src/__tests__/transmitter.test.ts
  src/transmitter.ts
Labels: bug

#804 Rebuild test app if changed
  script/integration_test_app
Labels: chore, dev happiness

#806 Bump agent to version 0c870c0
  scripts/extension/support/constants.js
Labels: chore

#798 Add version 3 release section to changelog
  CHANGELOG.md
Labels: writing

#807 Add support for the restify package
  .changesets/support-restify-package.md
  package-lock.json
  package.json
  src/client.ts
  test/restify/app/.gitignore
  test/restify/app/Dockerfile
  test/restify/app/package-lock.json
  test/restify/app/package.json
  test/restify/app/run.sh
  test/restify/app/src/app.ts
  test/restify/app/src/appsignal.ts
  test/restify/app/tsconfig.json
  test/restify/docker-compose.yml
  test/restify/tests/.rspec
  test/restify/tests/Dockerfile
  test/restify/tests/Gemfile
  test/restify/tests/Gemfile.lock
  test/restify/tests/spec/app_spec.rb
  test/restify/tests/spec/spec_helper.rb
Labels: enhancement
