Repository appsignal/appsignal-nodejs, pull requests merged in 2022-09, with the labels that each got.

#725 Otel request hooks
  package-lock.json
  package.json
  src/client.ts
  test/express-redis/app/package-lock.json
Labels: feature, opentelemetry

#726 Use sendSessionData config option properly
  src/client.ts
  src/config/options.ts
  src/interfaces/options.ts
Labels: bug, opentelemetry

#727 Refactor app tests
  test/express-apollo/docker-compose.yml
  test/express-apollo/tests/spec/app_spec.rb
  test/express-apollo/tests/spec/spec_helper.rb
  test/express-postgres/docker-compose.yml
  test/express-postgres/tests/spec/app_spec.rb
  test/express-postgres/tests/spec/spec_helper.rb
  test/express-redis/docker-compose.yml
  test/express-redis/tests/spec/app_spec.rb
  test/express-redis/tests/spec/spec_helper.rb
  test/express-yoga/docker-compose.yml
  test/express-yoga/tests/spec/app_spec.rb
  test/express-yoga/tests/spec/spec_helper.rb
  test/helpers/error_helper.rb
  test/helpers/express_helper.rb
  test/helpers/graphql_helper.rb
  test/helpers/http_helper.rb
  test/helpers/integration_helper.rb
  test/helpers/koa_helper.rb
  test/helpers/redis_helper.rb
  test/helpers/span.rb
  test/integration_helper.rb
  test/koa-mysql/docker-compose.yml
  test/koa-mysql/tests/spec/app_spec.rb
  test/koa-mysql/tests/spec/spec_helper.rb
Labels: dev happiness, opentelemetry

#729 Add Prisma support
  package-lock.json
  package.json
  src/client.ts
  test/express-prisma/app/.gitignore
  test/express-prisma/app/Dockerfile
  test/express-prisma/app/package-lock.json
  test/express-prisma/app/package.json
  test/express-prisma/app/prisma/migrations/20220915093834_default/migration.sql
  test/express-prisma/app/prisma/migrations/migration_lock.toml
  test/express-prisma/app/prisma/schema.prisma
  test/express-prisma/app/run.sh
  test/express-prisma/app/src/app.ts
  test/express-prisma/app/src/appsignal.ts
  test/express-prisma/app/src/seed.ts
  test/express-prisma/app/tsconfig.json
  test/express-prisma/docker-compose.yml
  test/express-prisma/tests/.rspec
  test/express-prisma/tests/Dockerfile
  test/express-prisma/tests/Gemfile
  test/express-prisma/tests/Gemfile.lock
  test/express-prisma/tests/spec/app_spec.rb
  test/express-prisma/tests/spec/spec_helper.rb
Labels: enhancement

#736 Config fixes
  src/client.ts
  src/interfaces/options.ts
Labels: chore

#737 Only initialise OpenTelemetry when active
  src/__tests__/client.test.ts
  src/client.ts
Labels: bug

#733 Clean the build dir upon `clean:ext` script
  package.json
Labels: chore

#740 Run Prisma integration test app on CI
  .semaphore/semaphore.yml
  build_matrix.yml
  test/express-prisma/app/package.json
  test/express-prisma/app/run.sh
Labels: bug
