Repository appsignal/appsignal-nodejs, pull requests merged in 2022-06, with the labels that each got.

#677 Ignore HTTP requests to socket.io
  packages/nodejs/.changesets/ignore-http-requests-to-socket-io.md
  packages/nodejs/src/instrumentation/http/lifecycle/incoming.ts
Labels: bug

#678 Fix removing wrapped event listeners
  packages/nodejs/.changesets/fix-removing-event-listeners-from-wrapped-event-emitters.md
  packages/nodejs/src/__tests__/scope.test.ts
  packages/nodejs/src/scope.ts
Labels: bug

#679 Remove Node 17 from the build matrix
  .semaphore/semaphore.yml
  Rakefile
  build_matrix.yml
Labels: chore

#680 Refactor scope internals
  packages/nodejs/src/__tests__/scope.test.ts
  packages/nodejs/src/scope.ts
Labels: chore

#681 Check if spans are open in the ScopeManager before setting as root or active
  packages/nodejs/.changesets/do-not-restore-closed-spans-from-within-withspan.md
  packages/nodejs/.changesets/do-not-restore-root-span-after-withcontext-callback-has-finished.md
  packages/nodejs/.changesets/don-t-return-closed-spans-in-withcontext-helper.md
  packages/nodejs/.changesets/only-allow-open-root-spans-to-be-set-as-root.md
  packages/nodejs/src/__tests__/scope.test.ts
  packages/nodejs/src/scope.ts
Labels: bug

#685 Runtime dep @opentelemetry/sdk-trace-base package
  package-lock.json
  packages/nodejs/.changesets/add-@opentelemetry-sdk-trace-base-runtime-dependency.md
  packages/nodejs/package.json
Labels: bug

#669 Remove AppSignal requirement for SpanProcessor
  packages/nodejs/.changesets/support-opentelemetry-root-spans-in-spanprocessor.md
  packages/nodejs/src/span_processor.ts
Labels: enhancement

#687 Improve error reporting on extension load failure
  packages/nodejs/.changesets/improve-error-message-on-extension-load-failure.md
  packages/nodejs/scripts/extension/report.js
  packages/nodejs/src/__tests__/extension.failure.test.ts
  packages/nodejs/src/diagnose.ts
  packages/nodejs/src/extension_wrapper.ts
  packages/nodejs/src/utils.ts
Labels: enhancement

#690 Create OpenTelemetry spans rather than importing
  .changesets/bump-agent-to-v-d573c9b.md
  .changesets/support-opentelemetry-errors.md
  ext/appsignal_extension.cpp
  scripts/extension/support/constants.js
  src/extension.ts
  src/extension_wrapper.ts
  src/span_processor.ts
Labels: enhancement

#691 Add demo function to restore demo functionality
  src/client.ts
  src/demo.ts
Labels: chore

#692 Update to Typescript 4.7.3
  package-lock.json
  packages/nodejs/src/bootstrap.ts
  packages/nodejs/src/diagnose.ts
  packages/nodejs/src/instrumentation/http/lifecycle/outgoing.ts
  packages/nodejs/src/scope.ts
  packages/nodejs/src/span.ts
Labels: chore

#693 Add Koa instrumentation
  src/client.ts
Labels: feature

#694 Add Redis 4 instrumentation to OpenTelemetry
  src/client.ts
Labels: enhancement

#695 Remove the mysql2 package peer dependency
  .changesets/remove-mysql2-peer-dependency.md
  package-lock.json
  package.json
Labels: chore
