Repository appsignal/appsignal-nodejs, pull requests merged in 2022-05, with the labels that each got.

#652 Add Node 18 to build matrix
  .semaphore/semaphore.yml
  build_matrix.yml
Labels: chore

#655 Update apollo-server-plugin-base dependency in CI
  .semaphore/semaphore.yml
  build_matrix.yml
Labels: chore

#656 Add createRootSpan function
  packages/nodejs/.changesets/add-createrootspan-function.md
  packages/nodejs/src/__tests__/scope.test.ts
  packages/nodejs/src/__tests__/tracer.test.ts
  packages/nodejs/src/instrumentation/http/lifecycle/incoming.ts
  packages/nodejs/src/interfaces/tracer.ts
  packages/nodejs/src/noops/tracer.ts
  packages/nodejs/src/scope.ts
  packages/nodejs/src/tracer.ts
Labels: enhancement

#653 Send HTTP Post requests body params for Express
  packages/express/.changesets/send-http-request-body-params-properly.md
  packages/express/src/middleware/index.ts
Labels: bug

#657 Ignore parent `NoopSpan` in `createSpan`
  packages/nodejs/src/__tests__/tracer.test.ts
  packages/nodejs/src/tracer.ts
Labels: bug

#651 Add OpenTelemetry span processor
  .gitignore
  package-lock.json
  packages/nodejs/.changesets/add-opentelemetry-span-processor.md
  packages/nodejs/ext/appsignal_extension.cpp
  packages/nodejs/package.json
  packages/nodejs/scripts/extension/support/constants.js
  packages/nodejs/src/__tests__/span.test.ts
  packages/nodejs/src/extension.ts
  packages/nodejs/src/extension_wrapper.ts
  packages/nodejs/src/index.ts
  packages/nodejs/src/interfaces/span.ts
  packages/nodejs/src/interfaces/span_processor.ts
  packages/nodejs/src/span_processor.ts
Labels: feature

#659 Import OpenTelemetry types rather than duplicate
  package-lock.json
  packages/nodejs/.changesets/use-opentelemetry-spanprocessor-interface-to-build-our-own-spanprocessor.md
  packages/nodejs/package.json
  packages/nodejs/src/interfaces/span_processor.ts
  packages/nodejs/src/span_processor.ts
Labels: chore

#661 Reenable Next.js flaky test
  packages/nextjs/test/spec/integration_spec.rb
Labels: chore

#663 Remove NPM 8.5.3 usage from CI matrix
  .semaphore/semaphore.yml
  build_matrix.yml
Labels: chore

#662 Remove README install instructions
  README.md
Labels: writing

#667 Bump agent to v-0b43802
  packages/nodejs/.changesets/bump-agent-to-v-0b43802.md
  packages/nodejs/scripts/extension/support/constants.js
Labels: enhancement

#670 Lock apollo-server package versions in CI
  .semaphore/semaphore.yml
  build_matrix.yml
Labels: chore

#671 Test against apollo-server 3.8
  .semaphore/semaphore.yml
  build_matrix.yml
Labels: chore

#673 Bump agent to v-1a8ac46
  packages/nodejs/.changesets/bump-agent-to-v-1a8ac46.md
  packages/nodejs/scripts/extension/support/constants.js
Labels: enhancement

#675 Don't transfer closed spans to new async contexts
  packages/nodejs/.changesets/do-not-transfer-closed-spans-for-new-async-contexts.md
  packages/nodejs/src/__tests__/scope.test.ts
  packages/nodejs/src/scope.ts
Labels: bug
