Repository appsignal/appsignal-nodejs, pull requests merged in 2023-10, with the labels that each got.

#945 Report Node.js route parameters for routes
  .changesets/report-express-route-parameters.md
  src/client.ts
  test/express-redis/app/src/app.ts
  test/express-redis/tests/spec/app_spec.rb
Labels: enhancement

#944 Update OpenTelemetry dependencies
  .changesets/update-opentelemetry-dependencies.md
  package-lock.json
  package.json
  test/express-redis/app/package.json
Labels: chore

#948 Bump agent to e8207c1
  .changesets/bump-agent-to-e8207c1.md
  scripts/extension/support/constants.js
Labels: enhancement

#949 Update OTEL Fastify dependency
  .changesets/update-fastify-dependency-to-make-it-compatible-with-fastify-5.md
  package-lock.json
  package.json
  test/fastify/app/package-lock.json
  test/fastify/app/package.json
  test/fastify/tests/spec/app_spec.rb
Labels: support, chore

#954 Fix Express error handler signature error
  .changesets/fix-types-compatibility-for-the-express-error-handler.md
  package-lock.json
  src/instrumentation/express/error_handler.ts
  test/express-redis/app/package-lock.json
Labels: bug
