Repository appsignal/appsignal-nodejs, pull requests merged in 2023-07, with the labels that each got.

#911 Warn if `appsignal.cjs` is missing
  src/cli/diagnose.ts
  src/config.ts
  src/diagnose.ts
Labels: dev happiness

#912 Add `RENDER_GIT_COMMIT` support
  .changesets/use-render_git_commit-as-revision.md
  scripts/extension/support/constants.js
Labels: chore

#914 Update version range to allow Prisma 5
  .changesets/support-prisma-5.md
  package-lock.json
  package.json
Labels: chore

#918 Bump agent to 32590eb
  .changesets/bump-agent-to-32590eb.md
  scripts/extension/support/constants.js
Labels: enhancement

#927 Diagnose client file errors
  src/cli/diagnose.ts
  src/diagnose.ts
Labels: bug

#929 Bump agent to 6bec691
  .changesets/bump-agent-to-6bec691.md
  scripts/extension/support/constants.js
Labels: enhancement

#925 Add --config flag to diagnose command.
  .changesets/add---config-flag-to-diagnose-command.md
  src/cli/diagnose.ts
  src/diagnose.ts
Labels: enhancement
