Repository appsignal/appsignal-nodejs, pull requests merged in 2023-01, with the labels that each got.

#823 Add Winston transport for logging
  .changesets/add-winston-transport.md
  src/__tests__/winston_transport.test.ts
  src/index.ts
  src/logger.ts
  src/winston_transport.ts
Labels: enhancement

#827 Bump Next.js test app package-lock.json file
  test/nextjs/app/package-lock.json
Labels: chore

#829 Remove package.json overrides
  package-lock.json
  package.json
Labels: chore

#819 Track restify request parameters
  .changesets/report-request-parameters-for-restify.md
  package-lock.json
  package.json
  src/client.ts
  test/restify/app/src/app.ts
  test/restify/tests/spec/app_spec.rb
Labels: enhancement

#826 Add Winston transport for logging
  .changesets/add-winston-transport.md
  src/__tests__/winston_transport.test.ts
  src/index.ts
  src/logger.ts
  src/winston_transport.ts
Labels: enhancement

#838 Add OpenTelemetry SDK start promise as a property
  .changesets/add-opentelemetry-sdk-initialization-to-client.md
  src/client.ts
Labels: bug, support

#840 Add instrumentationsLoaded as a helper
  .changesets/add-opentelemetry-sdk-initialization-to-client.md
  package-lock.json
  src/__tests__/helpers.test.ts
  src/client.ts
  src/helpers.ts
Labels: bug, support

#844 Bump agent 041b9c4
  .changesets/bump-agent-to-041b9c4.md
  package-lock.json
  scripts/extension/support/constants.js
  src/__tests__/span_processor.test.ts
  src/span.ts
Labels: enhancement

#842 Update prisma instrumentation package
  .changesets/update-prisma-instrumentation-package.md
  package-lock.json
  package.json
Labels: chore

#846 Bump agent to 050d7a5
  .changesets/bump-agent-to-050d7a5.md
  scripts/extension/support/constants.js
Labels: chore
