Repository appsignal/appsignal-nodejs, pull requests merged in 2024-04, with the labels that each got.

#1035 Bump agent to version 0.35.0
  .changesets/fix-unknown-method-in-next-js-performance-traces.md
  scripts/extension/support/constants.js
Labels: chore

#1039 Bump agent to version 0.35.1
  .changesets/fix-incorrect-http-methods-in-next-js-14.md
  scripts/extension/support/constants.js
Labels: bug

#1043 Update agent to 0.35.3
  scripts/extension/support/constants.js
Labels: chore

#1045 Bump agent to version 0.35.5
  .changesets/ignore-amqp-spans-if-they-re-root-spans-.md
  .changesets/log-debug-messages-for-metrics.md
  scripts/extension/support/constants.js
Labels: enhancement
