Repository appsignal/appsignal-nodejs, pull requests merged in 2024-02, with the labels that each got.

#979 Rename Integration to Internal Logger
  src/__tests__/client.test.ts
  src/__tests__/helpers.test.ts
  src/__tests__/integration_logger.test.ts
  src/__tests__/logger.test.ts
  src/client.ts
  src/helpers.ts
  src/internal_logger.ts
  src/logger.ts
  src/noops/index.ts
  src/noops/internal_logger.ts
Labels: chore, dev happiness

#982 Bump agent to version 0.33.0
  .changesets/cgroups-v1-cpu-percentage-normalization.md
  .changesets/cgroups-v2-fractional-cpu.md
  scripts/extension/support/constants.js
Labels: enhancement

#998 Bump agent to version 0.33.1
  .changesets/add-opentelemetry-histogram-support.md
  scripts/extension/support/constants.js
Labels: chore

#1000 Bump agent to version 0.33.2
  .changesets/fix-opentelemetry-chunked-export-requests.md
  scripts/extension/support/constants.js
Labels: enhancement
