Repository appsignal/appsignal-nodejs, pull requests merged in 2024-09, with the labels that each got.

#1091 Check in scheduler
  .changesets/check-in-scheduler.md
  .changesets/do-not-block-node-js-shutdown.md
  src/__tests__/check_in.test.ts
  src/__tests__/probes.test.ts
  src/__tests__/utils.test.ts
  src/check_in.ts
  src/check_in/cron.ts
  src/check_in/index.ts
  src/check_in/scheduler.ts
  src/client.ts
  src/probes/index.ts
  src/utils.ts
Labels: enhancement

#1129 Add agent release workflow
  .github/workflows/agent_release.yml
Labels: dev happiness

#1130 Improve TypeScript suggestions
  src/check_in/event.ts
  src/check_in/heartbeat.ts
  src/check_in/scheduler.ts
  src/config/configmap.ts
  src/extension_wrapper.ts
  src/heartbeat.ts
  src/internal/data.ts
  src/internal_logger.ts
  src/noops/internal_logger.ts
  src/noops/logger.ts
  src/noops/metrics.ts
  src/probes/index.ts
  src/probes/v8/index.ts
  src/span_processor.ts
  src/transmitter.ts
  src/utils.ts
  tsconfig.json
Labels: chore

#1123 Implement heartbeat check-ins
  .changesets/add-heartbeat-check-ins.md
  src/__tests__/check_in.test.ts
  src/__tests__/check_in/event.test.ts
  src/check_in/cron.ts
  src/check_in/event.ts
  src/check_in/heartbeat.ts
  src/check_in/index.ts
  src/check_in/scheduler.ts
  src/config/configmap.ts
  src/extension_wrapper.ts
  src/heartbeat.ts
  src/internal/data.ts
  src/internal_logger.ts
  src/noops/internal_logger.ts
  src/noops/logger.ts
  src/noops/metrics.ts
  src/probes/index.ts
  src/probes/v8/index.ts
  src/span_processor.ts
  src/transmitter.ts
  src/utils.ts
  tsconfig.json
Labels: feature

#1133 Move CI to GitHub Actions
  .eslintignore
  .github/workflows/ci.yml
  .rubocop.yml
  .semaphore/semaphore.yml
  Gemfile.lock
  README.md
  Rakefile
  build_matrix.yml
  package-lock.json
  script/integration_test_app
  script/lint_git
  script/setup
  test/express-prisma-postgres/docker-compose.yml
  test/helpers/integration_helper.rb
  test/helpers/span.rb
Labels: dev happiness
