Repository appsignal/appsignal-nodejs, pull requests merged in 2024-05, with the labels that each got.

#1046 Fix MySQL Docker container in Koa test app
  test/koa-mysql/app/src/app.ts
  test/koa-mysql/docker-compose.yml
Labels: chore

#1048 Remove stray conflict mark from package-lock
  package-lock.json
Labels: bug

#1049 Update Node.js versions in `.tool-versions` and CI
  .semaphore/semaphore.yml
  .tool-versions
  build_matrix.yml
Labels: chore

#1051 Only report extension load errors on start
  .changesets/improve-error-reporting-during-initialisation.md
  src/__tests__/client.test.ts
  src/__tests__/config.test.ts
  src/__tests__/extension.failure.test.ts
  src/client.ts
  src/config.ts
  src/extension.ts
  src/extension_wrapper.ts
Labels: dev happiness

#1050 Add missing required transitive dependencies
  .changesets/improve-compatibility-with-alternative-package-managers.md
  package-lock.json
  package.json
  src/client.ts
Labels: bug

#1052 Add `undici` (`fetch`) instrumentation
  .changesets/instrument-calls-to--fetch--in-node-js.md
  package-lock.json
  package.json
  src/client.ts
Labels: enhancement
