Repository appsignal/appsignal-nodejs, pull requests merged in 2024-01, with the labels that each got.

#972 Fix demo sample recognition by fixing the demo tag
  .changesets/fix-demo-sample-recognition.md
  src/demo.ts
Labels: bug

#971 Add OpenTelemetry diag logger
  .changesets/add-opentelemetry-diag-logger.md
  package-lock.json
  src/client.ts
Labels: dev happiness, enhancement

#973 Bump agent to bfe19b1
  .changesets/remove-deprecated-extension-functions.md
  .changesets/update-probes-0.5.4.md
  scripts/extension/support/constants.js
Labels: enhancement
